version: "3.9"
services:
  app:
    container_name: Korex_FE
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "4006:4006"
